### ISSUE TITLE
Exception: Unrecognised args for constructing Pixmap

### ISSUE THREAD

**Issue by Elonisme** [emacs-eaf/eaf-pdf-viewer#124]
**Describe the bug**
EAF-pdf-viewer显示白板，查看eaf buffer后显示如下信息：

> QApplication: invalid style override 'kvantum' passed, ignoring it.
> 	Available styles: Windows, Fusion
> Traceback (most recent call last):
>   File "/home/elon/emacs-application-framework/app/pdf-viewer/eaf_pdf_widget.py", line 499, in paintEvent
>     self.draw_scroll_pages(painter)
>   File "/home/elon/emacs-application-framework/app/pdf-viewer/eaf_pdf_widget.py", line 559, in draw_scroll_pages
>     (_, _, page_render_height) = self.get_page_render_info(self.start_page_index)
>                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/elon/emacs-application-framework/app/pdf-viewer/eaf_pdf_widget.py", line 411, in get_page_render_info
>     qpixmap = self.get_page_pixmap(index, self.scale * hidpi_scale_factor, self.rotation)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/elon/emacs-application-framework/app/pdf-viewer/eaf_pdf_widget.py", line 396, in get_page_pixmap
>     qpixmap = page.get_qpixmap(scale, self.get_inverted_mode(), self.inverted_image_mode)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/elon/emacs-application-framework/app/pdf-viewer/eaf_pdf_page.py", line 195, in get_qpixmap
>     pixmap = self.make_background_transparent(pixmap, (255,255,255))
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/elon/emacs-application-framework/app/pdf-viewer/eaf_pdf_page.py", line 260, in make_background_transparent
>     pixalpha = fitz.Pixmap(None, pixmap)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/elon/.local/lib/python3.11/site-packages/fitz/__init__.py", line 9690, in __init__
>     raise Exception( text)
> Exception: Unrecognised args for constructing Pixmap:
>     <class 'NoneType'>: None
>     <class 'fitz.Pixmap'>: Pixmap(DeviceRGB, (0, 0, 656, 928), 1)
> 
> Process *eaf* aborted (core dumped)

查询资料后发现是pymupdf依赖没有安装好，于是使用pip命令加--break-system-packages强制卸载pymupdf和fitz，然后按照同样强制pip重装fitz和pymupdf，安装顺序为先fitz然后再安装pymupdf，但是问题依然没有得到解决。

我使用arco linux，emacs为29，python版本为3.11

![Screenshot_20240129_121056](https://github.com/emacs-eaf/eaf-pdf-viewer/assets/87638888/fe8b10c6-a968-4976-92f2-a47a784b9608)
![Screenshot_20240129_121111](https://github.com/emacs-eaf/eaf-pdf-viewer/assets/87638888/07dab394-fcdd-4e4b-942b-0acd09e16ec6)

**Comment by metaescape** [comment]
pip install pymupdf-1.21.0 试试，或者其他比如 1.20.0 版本都试一下

**Comment by Elonisme** [comment]
> pip install pymupdf==1.21.0 试试，或者其他比如 1.20.0 版本都试一下

使用命令:
```bash
sudo pacman -R python-pymupdf 
sudo pip install pymupdf==1.21.0 --break-system-packages
```
问题解决
