### ISSUE TITLE
Cannot execute function: edit_annot_text

### ISSUE THREAD

**Issue by feiyongzhai** [emacs-eaf/eaf-pdf-viewer#67]
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.
```
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/home/yongfeizhai/.emacs.d/extensions/emacs-application-framework/eaf.py", line 365, in eval_function
    getattr(buffer, function_name)()
  File "/home/yongfeizhai/.emacs.d/extensions/emacs-application-framework/app/pdf-viewer/buffer.py", line 303, in edit_annot_text
    self.buffer_widget.annot_handler("edit")
  File "/home/yongfeizhai/.emacs.d/extensions/emacs-application-framework/app/pdf-viewer/buffer.py", line 1884, in annot_handler
    self.edited_annot_page = (annot, annot.parent.page)
AttributeError: 'Page' object has no attribute 'page'

```

**Describe the bug**
When mouse hover on an annotation, and press `M-e` will cause this problem

**Versions :**
 - eaf and eaf-pdf-viewer is the latest version
 - DE: GNOME 3.36.5
 - pymupdf 1.19.6
 - GNU Emacs 28.0.91 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-03-09

**Screenshots**
![image](https://user-images.githubusercontent.com/42181003/159443964-687804ae-1ed4-4d26-90d4-07a51d566bd7.png)

![image](https://user-images.githubusercontent.com/42181003/159444353-98e6621d-2673-4f51-8155-d7b4ea7fb980.png)

**Comment by luhuaei** [comment]
Fixed ef5fba8d1317348c4c74911407c0b80c75090f1d
