### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by TerryTsao** [emacs-eaf/eaf-pdf-viewer#68]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.

```
Traceback (most recent call last):
  File "/home/xx/.emacs.d.spacemacs/elpa-stable/28.0/develop/eaf-20220401.1719/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/xx/.emacs.d.spacemacs/elpa/28.0/develop/eaf-20220401.1719/eaf.py", line 386, in handle_input_response
    buffer.handle_input_response(callback_tag, callback_result)
  File "/home/xx/.emacs.d.spacemacs/elpa/28.0/develop/eaf-20220401.1719/app/pdf-viewer/eaf_pdf_buffer.py", line 134, in handle_input_response
    self.buffer_widget.search_text(str(result_content))
  File "/home/xx/.emacs.d.spacemacs/elpa/28.0/develop/eaf-20220401.1719/app/pdf-viewer/eaf_pdf_widget.py", line 798, in search_text
    quads_list = self.document.search_page_for(page_index, text, hit_max=999, quads=True)
TypeError: search_page_for() got an unexpected keyword argument 'hit_max'
```

**Describe the bug**

<kbd>C-s</kbd> does nothing. `*eaf*` buffer shows the above error.

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.

Hit <kbd>C-s</kbd>

**Expected behavior**

Successful search.

**Versions (please complete the following info):**
 - Distro and DE/WM: archlinux, KDE
 - Versions of Dependencies: qt5-legacy (should reproduce on master)
 - M-x emacs-version: GNU Emacs 28.0.92 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.4) of 2022-03-23

**Screenshots**

**Additional context**
pymupdf doc says `hit_max` is dropped since v1.18.2.

**Comment by TerryTsao** [comment]
What do DaLao们 think: is it better to add a `fitz` version check if-else, OR just remove this keyword and suggest users to upgrade to latest `pymupdf`?
