### ISSUE TITLE
Crash with specific file

### ISSUE THREAD

**Issue by shrubbroom** [emacs-eaf/eaf-pdf-viewer#72]
**Describe the bug**
The PDF viewer crashes as I scroll to the second page of specific pdf file.  The file can be downloaded from here https://electrovolt.ir/wp-content/uploads/2014/08/Design-of-Analog-CMOS-Integrated-Circuit-2nd-Edition-ElectroVolt.ir_.pdf

**To Reproduce**
Minimal configurations with `emacs -Q`

``` emacs-lisp
;; setup packages
(package-initialize)
(add-to-list 'load-path
             (concat user-emacs-directory
                     "site-packages/eaf"))
(setq eaf-python-command "/usr/bin/python3")
(require 'eaf)
(require 'eaf-pdf-viewer)
(require 'eaf-system-monitor)
(require 'eaf-image-viewer)
(require 'eaf-markdown-previewer)
(require 'eaf-org-previewer)
(require 'eaf-file-manager)
```

Open the pdf file above, scroll to the second page.  The pdf-viewer would crash.
**Versions (please complete the following info):**
 - Distro and DE/WM: i3wm
 - Versions of Dependencies: 
 ``` shell
local/python-pyqt6 6.3.0-1 (pyqt6)
    A set of Python bindings for the Qt6 toolkit
local/python-pyqt6-sip 13.3.1-1
    The sip module support for PyQt6
local/python-pyqt6-webengine 6.3.0-1 (pyqt6)
    Python bindings for QtWebEngine
```

EAF core and pdf viewer are on master branch.
 - M-x emacs-version: 28.0.92

**Additional context**
The log file is shown here
``` python
Traceback (most recent call last):
  File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/pdf-viewer/eaf_pdf_widget.py", line 374, in paintEvent
    qpixmap = self.get_page_pixmap(index, self.scale * hidpi_scale_factor, self.rotation)
  File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/pdf-viewer/eaf_pdf_widget.py", line 295, in get_page_pixmap
    page = self.document[index]
  File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/pdf-viewer/eaf_pdf_document.py", line 59, in __getitem__
    page = PdfPage(self.document[index], index, self.document.isPDF)
  File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/pdf-viewer/eaf_pdf_page.py", line 84, in __init__
    self._page_rawdict = self._init_page_rawdict()
  File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/pdf-viewer/eaf_pdf_page.py", line 99, in _init_page_rawdict
    set_page_crop_box(self.page)(self.clip)
  File "/usr/lib/python3.10/site-packages/fitz/fitz.py", line 6649, in set_cropbox
    return self._set_pagebox("CropBox", rect)
  File "/usr/lib/python3.10/site-packages/fitz/fitz.py", line 6644, in _set_pagebox
    raise ValueError("rect not in mediabox")
ValueError: rect not in mediabox

Process *eaf* aborted (core dumped)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffd68fa640 (LWP 220218)]
[New Thread 0x7fffd5eb1640 (LWP 220219)]
[New Thread 0x7fffd52c0640 (LWP 220220)]
[New Thread 0x7fffce572640 (LWP 220221)]
[New Thread 0x7fffcdbe2640 (LWP 220222)]
[New Thread 0x7fffcd252640 (LWP 220223)]
[New Thread 0x7fffc16e9640 (LWP 220224)]
[New Thread 0x7fffc0d59640 (LWP 220225)]
[New Thread 0x7fffabfff640 (LWP 220226)]
[New Thread 0x7fffab66f640 (LWP 220227)]
[New Thread 0x7fffaacdf640 (LWP 220228)]
[New Thread 0x7fffaa34f640 (LWP 220229)]
[New Thread 0x7fffa99bf640 (LWP 220230)]
[New Thread 0x7fffa902f640 (LWP 220231)]
[New Thread 0x7fff8bfff640 (LWP 220232)]
[New Thread 0x7fff83fff640 (LWP 220233)]
[New Thread 0x7fff8b66f640 (LWP 220234)]
[New Thread 0x7fff8acdf640 (LWP 220235)]
[New Thread 0x7fff8a34f640 (LWP 220236)]
[New Thread 0x7fff899bf640 (LWP 220237)]
[New Thread 0x7fff8902f640 (LWP 220238)]
[Thread 0x7fff8902f640 (LWP 220238) exited]
[New Thread 0x7fff8902f640 (LWP 220239)]
[New Thread 0x7fff8366f640 (LWP 220240)]
[New Thread 0x7fff82cdf640 (LWP 220241)]
[New Thread 0x7fff8234f640 (LWP 220242)]
[Thread 0x7fff8234f640 (LWP 220242) exited]
[New Thread 0x7fff8234f640 (LWP 220243)]
[Thread 0x7fff82cdf640 (LWP 220241) exited]
[Thread 0x7fff8234f640 (LWP 220243) exited]
[New Thread 0x7fff8234f640 (LWP 220244)]
[Thread 0x7fff8234f640 (LWP 220244) exited]
[New Thread 0x7fff8234f640 (LWP 220245)]
[Thread 0x7fff8234f640 (LWP 220245) exited]
[New Thread 0x7fff8234f640 (LWP 220246)]
[Thread 0x7fff8234f640 (LWP 220246) exited]
[New Thread 0x7fff8234f640 (LWP 220247)]
[Thread 0x7fff8234f640 (LWP 220247) exited]
[New Thread 0x7fff8234f640 (LWP 220248)]
[Thread 0x7fff8234f640 (LWP 220248) exited]
[New Thread 0x7fff8234f640 (LWP 220249)]
[Thread 0x7fff8234f640 (LWP 220249) exited]
[New Thread 0x7fff8234f640 (LWP 220250)]
[Thread 0x7fff8234f640 (LWP 220250) exited]
[New Thread 0x7fff8234f640 (LWP 220251)]
[Thread 0x7fff8234f640 (LWP 220251) exited]
[New Thread 0x7fff8234f640 (LWP 220252)]
[Thread 0x7fff8234f640 (LWP 220252) exited]
[New Thread 0x7fff8234f640 (LWP 220253)]
[Thread 0x7fff8234f640 (LWP 220253) exited]
[New Thread 0x7fff8234f640 (LWP 220254)]
[Thread 0x7fff8234f640 (LWP 220254) exited]
[New Thread 0x7fff8234f640 (LWP 220255)]
[Thread 0x7fff8234f640 (LWP 220255) exited]
[New Thread 0x7fff8234f640 (LWP 220256)]
[Thread 0x7fff8234f640 (LWP 220256) exited]
[New Thread 0x7fff8234f640 (LWP 220257)]
[Thread 0x7fff8234f640 (LWP 220257) exited]
[New Thread 0x7fff8234f640 (LWP 220258)]
[Thread 0x7fff8234f640 (LWP 220258) exited]
[New Thread 0x7fff8234f640 (LWP 220259)]
[Thread 0x7fff8234f640 (LWP 220259) exited]
[New Thread 0x7fff8234f640 (LWP 220260)]
[Thread 0x7fff8234f640 (LWP 220260) exited]
[New Thread 0x7fff8234f640 (LWP 220261)]
[Thread 0x7fff8234f640 (LWP 220261) exited]
[New Thread 0x7fff8234f640 (LWP 220278)]
[Thread 0x7fff8234f640 (LWP 220278) exited]
[New Thread 0x7fff8234f640 (LWP 220279)]
[Thread 0x7fff8234f640 (LWP 220279) exited]
[New Thread 0x7fff8234f640 (LWP 220282)]
[Thread 0x7fff8234f640 (LWP 220282) exited]
[New Thread 0x7fff8234f640 (LWP 220283)]
[Thread 0x7fff8234f640 (LWP 220283) exited]
[New Thread 0x7fff8234f640 (LWP 220284)]
[Thread 0x7fff8234f640 (LWP 220284) exited]
[New Thread 0x7fff8234f640 (LWP 220285)]
[Thread 0x7fff8234f640 (LWP 220285) exited]
[New Thread 0x7fff8234f640 (LWP 220286)]
[Thread 0x7fff8234f640 (LWP 220286) exited]
[New Thread 0x7fff8234f640 (LWP 220287)]
[Thread 0x7fff8234f640 (LWP 220287) exited]
[New Thread 0x7fff8234f640 (LWP 220288)]
[Thread 0x7fff8234f640 (LWP 220288) exited]
[New Thread 0x7fff8234f640 (LWP 220289)]
[Thread 0x7fff8234f640 (LWP 220289) exited]
[New Thread 0x7fff8234f640 (LWP 220290)]
[Thread 0x7fff8234f640 (LWP 220290) exited]
[New Thread 0x7fff8234f640 (LWP 220291)]
[Thread 0x7fff8234f640 (LWP 220291) exited]
[New Thread 0x7fff8234f640 (LWP 220292)]
[Thread 0x7fff8234f640 (LWP 220292) exited]
[New Thread 0x7fff8234f640 (LWP 220293)]
[Thread 0x7fff8234f640 (LWP 220293) exited]
[New Thread 0x7fff8234f640 (LWP 220294)]
[Thread 0x7fff8234f640 (LWP 220294) exited]
[New Thread 0x7fff8234f640 (LWP 220295)]
[Thread 0x7fff8234f640 (LWP 220295) exited]
[New Thread 0x7fff8234f640 (LWP 220296)]
[Thread 0x7fff8234f640 (LWP 220296) exited]
[New Thread 0x7fff8234f640 (LWP 220297)]
[Thread 0x7fff8234f640 (LWP 220297) exited]
[New Thread 0x7fff8234f640 (LWP 220298)]
[Thread 0x7fff8234f640 (LWP 220298) exited]
[New Thread 0x7fff8234f640 (LWP 220299)]
[Thread 0x7fff8234f640 (LWP 220299) exited]
[New Thread 0x7fff8234f640 (LWP 220300)]
[Thread 0x7fff8234f640 (LWP 220300) exited]
[New Thread 0x7fff8234f640 (LWP 220302)]
[Thread 0x7fff8234f640 (LWP 220302) exited]
[New Thread 0x7fff8234f640 (LWP 220303)]
[Thread 0x7fff8234f640 (LWP 220303) exited]
[New Thread 0x7fff8234f640 (LWP 220304)]
[Thread 0x7fff8234f640 (LWP 220304) exited]
[New Thread 0x7fff8234f640 (LWP 220305)]
[Thread 0x7fff8234f640 (LWP 220305) exited]
[New Thread 0x7fff8234f640 (LWP 220306)]
[Thread 0x7fff8234f640 (LWP 220306) exited]
[New Thread 0x7fff8234f640 (LWP 220307)]
[Thread 0x7fff8234f640 (LWP 220307) exited]
[New Thread 0x7fff8234f640 (LWP 220308)]
[Thread 0x7fff8234f640 (LWP 220308) exited]
[New Thread 0x7fff8234f640 (LWP 220309)]
[Thread 0x7fff8234f640 (LWP 220309) exited]
[New Thread 0x7fff8234f640 (LWP 220310)]
[Thread 0x7fff8234f640 (LWP 220310) exited]
[New Thread 0x7fff8234f640 (LWP 220311)]
[Thread 0x7fff8234f640 (LWP 220311) exited]
[New Thread 0x7fff8234f640 (LWP 220312)]
[Thread 0x7fff8234f640 (LWP 220312) exited]
[New Thread 0x7fff8234f640 (LWP 220313)]
[Thread 0x7fff8234f640 (LWP 220313) exited]
[New Thread 0x7fff8234f640 (LWP 220314)]
[Thread 0x7fff8234f640 (LWP 220314) exited]
[New Thread 0x7fff8234f640 (LWP 220315)]
[Thread 0x7fff8234f640 (LWP 220315) exited]
[New Thread 0x7fff8234f640 (LWP 220316)]
[Thread 0x7fff8234f640 (LWP 220316) exited]
[New Thread 0x7fff8234f640 (LWP 220317)]
[Thread 0x7fff8234f640 (LWP 220317) exited]
[New Thread 0x7fff8234f640 (LWP 220318)]
[Thread 0x7fff8234f640 (LWP 220318) exited]
[New Thread 0x7fff8234f640 (LWP 220319)]
[Thread 0x7fff8234f640 (LWP 220319) exited]
[New Thread 0x7fff8234f640 (LWP 220320)]
[Thread 0x7fff8234f640 (LWP 220320) exited]
[New Thread 0x7fff8234f640 (LWP 220321)]
[Thread 0x7fff8234f640 (LWP 220321) exited]
[New Thread 0x7fff8234f640 (LWP 220322)]
[Thread 0x7fff8234f640 (LWP 220322) exited]
[New Thread 0x7fff8234f640 (LWP 220323)]
[Thread 0x7fff8234f640 (LWP 220323) exited]
[New Thread 0x7fff8234f640 (LWP 220324)]
[Thread 0x7fff8234f640 (LWP 220324) exited]
[New Thread 0x7fff8234f640 (LWP 220325)]
[Thread 0x7fff8234f640 (LWP 220325) exited]
[New Thread 0x7fff8234f640 (LWP 220326)]
[Thread 0x7fff8234f640 (LWP 220326) exited]
[New Thread 0x7fff8234f640 (LWP 220327)]
[Thread 0x7fff8234f640 (LWP 220327) exited]
[New Thread 0x7fff8234f640 (LWP 220328)]
[Thread 0x7fff8234f640 (LWP 220328) exited]
[New Thread 0x7fff8234f640 (LWP 220329)]
[Thread 0x7fff8234f640 (LWP 220329) exited]
[New Thread 0x7fff8234f640 (LWP 220330)]
[Thread 0x7fff8234f640 (LWP 220330) exited]
[New Thread 0x7fff8234f640 (LWP 220331)]
[New Thread 0x7fff82cdf640 (LWP 220332)]
[Thread 0x7fff82cdf640 (LWP 220332) exited]
[Thread 0x7fff8234f640 (LWP 220331) exited]
Traceback (most recent call last):
  File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/pdf-viewer/eaf_pdf_widget.py", line 374, in paintEvent
    qpixmap = self.get_page_pixmap(index, self.scale * hidpi_scale_factor, self.rotation)
  File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/pdf-viewer/eaf_pdf_widget.py", line 295, in get_page_pixmap
    page = self.document[index]
  File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/pdf-viewer/eaf_pdf_document.py", line 59, in __getitem__
    page = PdfPage(self.document[index], index, self.document.isPDF)
  File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/pdf-viewer/eaf_pdf_page.py", line 84, in __init__
    self._page_rawdict = self._init_page_rawdict()
  File "/home/shrubbroom/.emacs.d/site-packages/eaf/app/pdf-viewer/eaf_pdf_page.py", line 99, in _init_page_rawdict
    set_page_crop_box(self.page)(self.clip)
  File "/usr/lib/python3.10/site-packages/fitz/fitz.py", line 6649, in set_cropbox
    return self._set_pagebox("CropBox", rect)
  File "/usr/lib/python3.10/site-packages/fitz/fitz.py", line 6644, in _set_pagebox
    raise ValueError("rect not in mediabox")
ValueError: rect not in mediabox

Thread 1 "python3" received signal SIGABRT, Aborted.
0x00007ffff7a6234c in __pthread_kill_implementation () from /usr/lib/libc.so.6
#0  0x00007ffff7a6234c in __pthread_kill_implementation () at /usr/lib/libc.so.6
#1  0x00007ffff7a154b8 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff79ff534 in abort () at /usr/lib/libc.so.6
#3  0x00007fffeb06d071 in  () at /usr/lib/libQt6Core.so.6
#4  0x00007fffeb06d3a5 in qt_assert(char const*, char const*, int) () at /usr/lib/libQt6Core.so.6
#5  0x00007fffd7d14272 in  () at /usr/lib/python3.10/site-packages/PyQt6/QtCore.abi3.so
#6  0x00007fffd7e34b28 in  () at /usr/lib/python3.10/site-packages/PyQt6/sip.cpython-310-x86_64-linux-gnu.so
#7  0x00007fffd76bc3ca in  () at /usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so
#8  0x00007ffff695240e in QWidget::event(QEvent*) () at /usr/lib/libQt6Widgets.so.6
#9  0x00007fffd76bc95c in  () at /usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so
#10 0x00007ffff690db5d in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#11 0x00007fffd7691c57 in  () at /usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so
#12 0x00007fffeb0f143a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#13 0x00007ffff6941d3c in QWidgetPrivate::sendPaintEvent(QRegion const&) () at /usr/lib/libQt6Widgets.so.6
#14 0x00007ffff6943b1c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt6Widgets.so.6
#15 0x00007ffff69460ef in QWidgetPrivate::render(QPaintDevice*, QPoint const&, QRegion const&, QFlags<QWidget::RenderFlag>) () at /usr/lib/libQt6Widgets.so.6
#16 0x00007ffff6946539 in QWidget::render(QPainter*, QPoint const&, QRegion const&, QFlags<QWidget::RenderFlag>) () at /usr/lib/libQt6Widgets.so.6
#17 0x00007ffff6c79636 in QGraphicsProxyWidget::paint(QPainter*, QStyleOptionGraphicsItem const*, QWidget*) () at /usr/lib/libQt6Widgets.so.6
#18 0x00007ffff6ca0828 in  () at /usr/lib/libQt6Widgets.so.6
#19 0x00007ffff6c8baa8 in  () at /usr/lib/libQt6Widgets.so.6
#20 0x00007ffff6c8c5e9 in  () at /usr/lib/libQt6Widgets.so.6
#21 0x00007ffff6cbcc17 in QGraphicsView::paintEvent(QPaintEvent*) () at /usr/lib/libQt6Widgets.so.6
#22 0x00007fffd75b5b04 in  () at /usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so
#23 0x00007ffff695240e in QWidget::event(QEvent*) () at /usr/lib/libQt6Widgets.so.6
#24 0x00007ffff69dc7e7 in QFrame::event(QEvent*) () at /usr/lib/libQt6Widgets.so.6
#25 0x00007fffd75b69cc in  () at /usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so
#26 0x00007fffeb0f0470 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#27 0x00007ffff690db4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#28 0x00007fffd7691c57 in  () at /usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so
#29 0x00007fffeb0f143a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#30 0x00007ffff6941d3c in QWidgetPrivate::sendPaintEvent(QRegion const&) () at /usr/lib/libQt6Widgets.so.6
#31 0x00007ffff6943b1c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt6Widgets.so.6
#32 0x00007ffff695ffc4 in  () at /usr/lib/libQt6Widgets.so.6
#33 0x00007ffff6952106 in QWidget::event(QEvent*) () at /usr/lib/libQt6Widgets.so.6
#34 0x00007fffd76bc95c in  () at /usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so
#35 0x00007ffff690db5d in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#36 0x00007fffd7691c57 in  () at /usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so
#37 0x00007fffeb0f143a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#38 0x00007fffeb0f1608 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt6Core.so.6
#39 0x00007ffff6c94d28 in  () at /usr/lib/libQt6Widgets.so.6
#40 0x00007fffeb13774b in QObject::event(QEvent*) () at /usr/lib/libQt6Core.so.6
#41 0x00007fffd75c9a9c in  () at /usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so
#42 0x00007ffff690db5d in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#43 0x00007fffd7691c57 in  () at /usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so
#44 0x00007fffeb0f143a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#45 0x00007fffeb0f1608 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt6Core.so.6
#46 0x00007fffeb30c768 in  () at /usr/lib/libQt6Core.so.6
#47 0x00007fffe7e87163 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#48 0x00007fffe7edd9e9 in  () at /usr/lib/libglib-2.0.so.0
#49 0x00007fffe7e846c5 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#50 0x00007fffeb30a8d0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#51 0x00007fffeb0f994b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#52 0x00007fffeb0f3fb9 in QCoreApplication::exec() () at /usr/lib/libQt6Core.so.6
#53 0x00007fffd768d47e in  () at /usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so
#54 0x00007ffff7d2d488 in  () at /usr/lib/libpython3.10.so.1.0
#55 0x00007ffff7d26ddb in _PyObject_MakeTpCall () at /usr/lib/libpython3.10.so.1.0
#56 0x00007ffff7d221c5 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.10.so.1.0
#57 0x00007ffff7d1b752 in  () at /usr/lib/libpython3.10.so.1.0
#58 0x00007ffff7dd2f64 in PyEval_EvalCode () at /usr/lib/libpython3.10.so.1.0
#59 0x00007ffff7de2df4 in  () at /usr/lib/libpython3.10.so.1.0
#60 0x00007ffff7dde7bb in  () at /usr/lib/libpython3.10.so.1.0
#61 0x00007ffff7c7ac13 in  () at /usr/lib/libpython3.10.so.1.0
#62 0x00007ffff7c7a893 in _PyRun_SimpleFileObject () at /usr/lib/libpython3.10.so.1.0
#63 0x00007ffff7c7b228 in _PyRun_AnyFileObject () at /usr/lib/libpython3.10.so.1.0
#64 0x00007ffff7def6ab in Py_RunMain () at /usr/lib/libpython3.10.so.1.0
#65 0x00007ffff7dc398d in Py_BytesMain () at /usr/lib/libpython3.10.so.1.0
#66 0x00007ffff7a00310 in __libc_start_call_main () at /usr/lib/libc.so.6
#67 0x00007ffff7a003c1 in __libc_start_main_impl () at /usr/lib/libc.so.6
#68 0x0000555555555045 in _start ()

Process *eaf* finished
```

**Comment by manateelazycat** [comment]
I have push commit https://github.com/emacs-eaf/eaf-pdf-viewer/commit/fd00c611aa6d21452f0298fd45c2a2ebf2806787 to fix this issue.

@luhuaei Please adjust it if this patch is not right.
