### ISSUE TITLE
Crash with large PDF and Chinese chars after the second compilation with auctex

### ISSUE THREAD

**Issue by allenryb** [emacs-eaf/eaf-pdf-viewer#75]
**Describe the bug**

使用 `auctex` 编译文件， `eaf-pdf-viewer` 预览。
当文件中包含大量中文且页码很多时，第一次编译顺利通过且预览顺利。
但是稍作修改后第二次编译，PDF 文件顺利生成，但 `eaf-pdf-viewer buffer` 就显示空白。

`*eaf*` 中的信息如下 （前两行是打开的时候就有的）
```
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: Windows, Fusion
Failed to watch callback
Traceback (most recent call last):
  File "/home/allenryb/.emacs.d/site-lisp/emacs-application-framework/app/pdf-viewer/eaf_pdf_widget.py", line 374, in paintEvent
    qpixmap = self.get_page_pixmap(index, self.scale * hidpi_scale_factor, self.rotation)
  File "/home/allenryb/.emacs.d/site-lisp/emacs-application-framework/app/pdf-viewer/eaf_pdf_widget.py", line 295, in get_page_pixmap
    page = self.document[index]
  File "/home/allenryb/.emacs.d/site-lisp/emacs-application-framework/app/pdf-viewer/eaf_pdf_document.py", line 59, in __getitem__
    page = PdfPage(self.document[index], index, self.document.isPDF)
  File "/home/allenryb/.local/lib/python3.10/site-packages/fitz/fitz.py", line 5571, in __getitem__
    raise IndexError("page not in document")
IndexError: page not in document

Process *eaf* aborted (core dumped)
```

**To Reproduce**

我使用以下 TeX 代码测试。`zhlipsum`是用来生成中文字段的，生成的 PDF 总计 78 页。
TeX 文件中有 4 个 `section`，如果删除 1 个 `section`，那就不会出现上面的问题。
如果文件中是全英文，那也不会出现上面的问题。

```
\documentclass{article}
\usepackage{zhlipsum}
\usepackage[fontset=none,UTF8]{ctex}
\setCJKmainfont{Sarasa UI SC}

\begin{document}

\section{S1}

\zhlipsum[-]

If we want dummy text in our document then we generally search for lorem ipsum text generators and copy-paste those texts/paragraphs in our document.

\section{S2}

\zhlipsum[-]

If we want dummy text in our document then we generally search for lorem ipsum text generators and copy-paste those texts/paragraphs in our document.

\section{S3}

\zhlipsum[-]

If we want dummy text in our document then we generally search for lorem ipsum text generators and copy-paste those texts/paragraphs in our document.

\section{S4}

\zhlipsum[-]

If we want dummy text in our document then we generally search for lorem ipsum text generators and copy-paste those texts/paragraphs in our document.

\end{document}

%%% Local Variables: 
%%% coding: utf-8
%%% mode: latex
%%% TeX-engine: xetex
%%% End: 
```

**Expected behavior**
希望能正常运行。

**Versions (please complete the following info):**
我用的系统是 archlinux，`emace-version` 是 28.1

**Comment by manateelazycat** [comment]
看着log像重新编译后， PDF页数发生变化导致的 Index 错误

我不用 LaTeX， 估计要看懂 LaTeX 的 EAF 开发者有没有空了。

**Comment by manateelazycat** [comment]
看看 https://github.com/emacs-eaf/eaf-pdf-viewer/commit/dc83a3db41d56e36283c57308ab15d7855b38041 这个补丁是否修正了这个问题？

**Comment by allenryb** [comment]
> 看看 [dc83a3d](https://github.com/emacs-eaf/eaf-pdf-viewer/commit/dc83a3db41d56e36283c57308ab15d7855b38041) 这个补丁是否修正了这个问题？

非常感谢，我近期的电脑配置发生了一些变化，可能需要一段时间重新调整下配置进而来测试，抱歉。

**Comment by smallzhan** [comment]
嗯，拿那个 tex 文件可以复现。

应该可以了，主要问题就是还在生成 pdf 的时候去打开 pdf 了，所以打不开，原来的实现方式是发现 fileChanged 的 signal 之后 sleep 0.5s 再去打开，但是如果文件大，可能 0.5s 不够，所以用了个QTimer， 一个 0.5s 不成功就再等 0.5s 去读取，直到成功。

**Comment by manateelazycat** [comment]
大佬， 给力， 给力
