### ISSUE TITLE
pdf添加标注报错

### ISSUE THREAD

**Issue by lyjdwh** [emacs-eaf/eaf-pdf-viewer#80]
**Describe the bug**
当给pdf添加高亮，下划线，波浪线等等标注时，报如下错误
```
Traceback (most recent call last):
  File "/home/liuyan/bin/eaf/eaf.py", line 368, in eval_function
    getattr(buffer, function_name)()
  File "/home/liuyan/bin/eaf/app/pdf-viewer/eaf_pdf_buffer.py", line 242, in add_annot_highlight
    self.buffer_widget.annot_select_char_area("highlight")
  File "/home/liuyan/bin/eaf/app/pdf-viewer/eaf_pdf_widget.py", line 895, in annot_select_char_area
    new_annot = page.addHighlightAnnot(quads)
  File "/home/liuyan/bin/eaf/app/pdf-viewer/eaf_pdf_page.py", line 92, in __getattr__
    return getattr(self.page, attr)
AttributeError: 'Page' object has no attribute 'addHighlightAnnot'
Traceback (most recent call last):
  File "/home/liuyan/bin/eaf/eaf.py", line 368, in eval_function
    getattr(buffer, function_name)()
  File "/home/liuyan/bin/eaf/app/pdf-viewer/eaf_pdf_buffer.py", line 256, in add_annot_squiggly
    self.buffer_widget.annot_select_char_area("squiggly")
  File "/home/liuyan/bin/eaf/app/pdf-viewer/eaf_pdf_widget.py", line 907, in annot_select_char_area
    new_annot = page.addSquigglyAnnot(quads)
  File "/home/liuyan/bin/eaf/app/pdf-viewer/eaf_pdf_page.py", line 92, in __getattr__
    return getattr(self.page, attr)
AttributeError: 'Page' object has no attribute 'addSquigglyAnnot'
```

**To Reproduce**

打开一个pdf文件，选择文本，标注（高亮，下划线。。。）

**Expected behavior**

能够正确标注

**Versions (please complete the following info):**
 - Distro and DE/WM: manjaro dwm
 - Versions of Dependencies: 最新
 - M-x emacs-version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-06-26

**Comment by manateelazycat** [comment]
@luhuaei can you help fix? thanks

**Comment by lyjdwh** [comment]
another similiar bug
```
Traceback (most recent call last):
  File "/home/liuyan/bin/eaf/app/pdf-viewer/eaf_pdf_widget.py", line 376, in paintEvent
    qpixmap = self.get_page_pixmap(index, self.scale * hidpi_scale_factor, self.rotation)
  File "/home/liuyan/bin/eaf/app/pdf-viewer/eaf_pdf_widget.py", line 301, in get_page_pixmap
    page.add_mark_link()
  File "/home/liuyan/bin/eaf/app/pdf-viewer/eaf_pdf_page.py", line 278, in add_mark_link
    if self.page.firstLink:
AttributeError: 'Page' object has no attribute 'firstLink'. Did you mean: 'first_link'?

Process *eaf* aborted (core dumped)
```
