### ISSUE TITLE
Error pdf trought ssh

### ISSUE THREAD

**Issue by rromoli** [emacs-eaf/eaf-pdf-viewer#82]
**Describe the bug**
Unable to open pdf through ssh connection. The same pdf is correctly opened from local. This is the tracebug from the eaf buffer:

```
Saved session:  /home/r/.emacs.d/elpa/27.2/develop/eaf-20220629.133/app/pdf-viewer/eaf_pdf_buffer.py /home/r/Downloads/GC_analysis.pdf 0:2.69281045751634:fit_to_width:True:0
Traceback (most recent call last):
  File "/home/r/.emacs.d/elpa/27.2/develop/eaf-20220629.133/app/pdf-viewer/eaf_pdf_widget.py", line 338, in resizeEvent
    self.update_scale()
  File "/home/r/.emacs.d/elpa/27.2/develop/eaf-20220629.133/app/pdf-viewer/eaf_pdf_widget.py", line 540, in update_scale
    self.scale_to_width()
  File "/home/r/.emacs.d/elpa/27.2/develop/eaf-20220629.133/app/pdf-viewer/eaf_pdf_widget.py", line 533, in scale_to_width
    self.scale_to(self.rect().width() * 1.0 / self.page_width)
AttributeError: 'PdfViewerWidget' object has no attribute 'page_width'
Traceback (most recent call last):
  File "/home/r/.emacs.d/elpa/27.2/develop/eaf-20220629.133/app/pdf-viewer/eaf_pdf_widget.py", line 338, in resizeEvent
    self.update_scale()
  File "/home/r/.emacs.d/elpa/27.2/develop/eaf-20220629.133/app/pdf-viewer/eaf_pdf_widget.py", line 540, in update_scale
    self.scale_to_width()
  File "/home/r/.emacs.d/elpa/27.2/develop/eaf-20220629.133/app/pdf-viewer/eaf_pdf_widget.py", line 533, in scale_to_width
    self.scale_to(self.rect().width() * 1.0 / self.page_width)
AttributeError: 'PdfViewerWidget' object has no attribute 'page_width'

Process *eaf* aborted (core dumped)

```

**Versions (please complete the following info):**
 - Distro and DE/WM: Fedora Linux 36, Gnome 42.3 (Wayland), remote is Debian 11
 - Versions of Dependencies: eaf-20220629.133
 - M-x emacs-version: GNU Emacs 27.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.31, cairo version 1.17.4) of 2022-03-24

**Comment by luhuaei** [comment]
> open pdf through ssh connection.

How do this? use tramp? Never tried before open pdf through ssh :(

Do you `*Message*` buffer with  `Failed to load PDF file!` info?

**Comment by manateelazycat** [comment]
Upload pdf file?

**Comment by rromoli** [comment]
@luhuaei Yes I use tramp to open remote files. From the `*Message* `I get only this regardless thi action: `[EAF/pdf-viewer] Opening /ssh:erre:/home/cism/Data/2021/Giulia/GC_analysis.pdf`

@manateelazycat any pdf prodeces the same error

**Comment by manateelazycat** [comment]
EAF not support tramp, tramp is bad performance  implementation, sorry this issue don't know how to fix
