### ISSUE TITLE
eaf-pdf-viewer cannot open PDF compiled from LaTex when changes are made

### ISSUE THREAD

**Issue by XushanLu** [emacs-eaf/eaf-pdf-viewer#84]
Run git pull and .install-eaf.py and the problem persists.

**Describe the bug**

EAF-pdf-viewer can successfully open if the LaTex file is compiled for the first time. But it cannot be reopened when the LaTex file is changed and recompiled. 

**To Reproduce**

- Open a LaTex file and compile it. 
- Make a random change to the LaTex file and then re-compile it

**Expected behavior**

PDF file is reopened with the newest changes.

**Versions (please complete the following info):**
 - Distro and DE/WM: Ubuntu 22.04 with WSL 2
 - Versions of Dependencies:
 - M-x emacs-version: GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2022-05-31

**Additional context**
I am running Spacemacs with the following lines added to my .spacemacs file under `(defun dotspacemacs/user-config ()`
```lisp
  ;; Make EAF-PDF the default viewer for Tex PDF export
  (require 'auctex-latexmk)
  (add-to-list 'TeX-command-list '("XeLaTeX" "%`xelatex --synctex=1%(mode)%' %t" TeX-run-TeX nil t))
  (add-to-list 'TeX-view-program-list '("eaf" eaf-pdf-synctex-forward-view))
  (add-to-list 'TeX-view-program-selection '(output-pdf "eaf"))
```

** Error message in the *Message* buffer
`
error in process sentinel: eaf-epc-net-send: Process epc con 4 not running
error in process sentinel: Process epc con 4 not running
`

** Error message in the *eaf* buffer
```
Failed to watch callback
Traceback (most recent call last):
  File "/home/xsl/.emacs.d/elpa/28.1/develop/eaf-20220826.26/app/pdf-viewer/eaf_pdf_widget.py", line 376, in paintEvent
    qpixmap = self.get_page_pixmap(index, self.scale * hidpi_scale_factor, self.rotation)
  File "/home/xsl/.emacs.d/elpa/28.1/develop/eaf-20220826.26/app/pdf-viewer/eaf_pdf_widget.py", line 296, in get_page_pixmap
    page = self.document[index]
  File "/home/xsl/.emacs.d/elpa/28.1/develop/eaf-20220826.26/app/pdf-viewer/eaf_pdf_document.py", line 59, in __getitem__
    page = PdfPage(self.document[index], index, self.document.is_pdf)
  File "/home/xsl/.local/lib/python3.9/site-packages/fitz/fitz.py", line 5357, in __getitem__
    raise IndexError("page not in document")
IndexError: page not in document

Process *eaf* aborted
```

**Comment by XushanLu** [comment]
Okay, I just saw [this issue](https://github.com/emacs-eaf/eaf-pdf-viewer/issues/75#issue-1241716016), and they are likely the same thing.
